# Generated by Django 3.1.5 on 2021-01-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_token', models.CharField(max_length=250, verbose_name='ТГ токен')),
                ('tg_chat_id', models.CharField(max_length=100, verbose_name='Чат ID')),
                ('tg_text', models.TextField(help_text='Не более 4096 символов!', max_length=4096, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Настройки ТГ',
                'verbose_name_plural': 'Настройки ТГ',
            },
        ),
    ]
